cross_target_platform:
  - linux-64                            # [linux64]
  - linux-aarch64                       # [linux64 or aarch64]
  - linux-ppc64le                       # [linux64 or ppc64le]
  - osx-64                              # [linux64 or (osx and x86_64)]
  - osx-arm64                           # [linux64 or (osx and x86_64) or (osx and arm64)]
  - win-64                              # [linux64 or (osx and x86_64) or win64]
rust_arch:
  - x86_64-unknown-linux-gnu            # [linux64]
  - aarch64-unknown-linux-gnu           # [linux64 or aarch64]
  - powerpc64le-unknown-linux-gnu       # [linux64 or ppc64le]
  - x86_64-apple-darwin                 # [linux64 or (osx and x86_64)]
  - aarch64-apple-darwin                # [linux64 or (osx and x86_64) or (osx and arm64)]
  - x86_64-pc-windows-msvc              # [linux64 or (osx and x86_64) or win64]
rust_arch_env_build:
  - X86_64_UNKNOWN_LINUX_GNU            # [linux64]
  - AARCH64_UNKNOWN_LINUX_GNU           # [aarch64]
  - POWERPC64LE_UNKNOWN_LINUX_GNU       # [ppc64le]
  - X86_64_APPLE_DARWIN                 # [osx and x86_64]
  - AARCH64_APPLE_DARWIN                # [osx and arm64]
  - X86_64_PC_WINDOWS_MSVC              # [win64]
rust_arch_env:
  - X86_64_UNKNOWN_LINUX_GNU            # [linux64]
  - AARCH64_UNKNOWN_LINUX_GNU           # [linux64 or aarch64]
  - POWERPC64LE_UNKNOWN_LINUX_GNU       # [linux64 or ppc64le]
  - X86_64_APPLE_DARWIN                 # [linux64 or (osx and x86_64)]
  - AARCH64_APPLE_DARWIN                # [linux64 or (osx and x86_64) or (osx and arm64)]
  - X86_64_PC_WINDOWS_MSVC              # [linux64 or (osx and x86_64) or win64]
rust_default_cc_build:
  - x86_64-conda-linux-gnu-cc           # [linux64]
  - aarch64-conda-linux-gnu-cc          # [aarch64]
  - powerpc64le-conda-linux-gnu-cc      # [ppc64le]
  - x86_64-apple-darwin13.4.0-clang     # [osx and x86_64]
  - arm64-apple-darwin20.0.0-clang      # [osx and arm64]
  - clang-cl                            # [win64]
rust_default_cc:
  - x86_64-conda-linux-gnu-cc           # [linux64]
  - aarch64-conda-linux-gnu-cc          # [linux64 or aarch64]
  - powerpc64le-conda-linux-gnu-cc      # [linux64 or ppc64le]
  - x86_64-apple-darwin13.4.0-clang     # [linux64 or (osx and x86_64)]
  - arm64-apple-darwin20.0.0-clang      # [linux64 or (osx and x86_64) or (osx and arm64)]
  - clang-cl                            # [linux64 or (osx and x86_64) or win64]
MACOSX_SDK_VERSION:
  - 11.0
MACOSX_DEPLOYMENT_TARGET:
  - 10.9
version:
  - 1.46.0
  - 1.49.0
  - 1.49.0.dev20201015
channel_sources:
  - conda-forge
  - conda-forge
  - conda-forge/label/rust_dev,conda-forge
channel_targets:
  - conda-forge main
  - conda-forge main
  - conda-forge rust_dev
zip_keys:
  - - cross_target_platform
    - rust_arch
    - rust_arch_env
    - rust_default_cc
  - - version
    - channel_sources
    - channel_targets
