# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic



matrix:
  include:
    - env: CONFIG=linux_ppc64le_channel_targetsconda-forge_mainversion1.46.0 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_channel_targetsconda-forge_mainversion1.49.0 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_channel_targetsconda-forge_rust_devversion1.49.0.dev20201015 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"
  - export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi