MACOSX_DEPLOYMENT_TARGET:
- '0'
MACOSX_SDK_VERSION:
- '0'
cdt_name:
- cos6
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cross_target_platform:
- linux-ppc64le
docker_image:
- quay.io/condaforge/linux-anvil-comp7
rust_arch:
- powerpc64le-unknown-linux-gnu
rust_arch_env:
- POWERPC64LE_UNKNOWN_LINUX_GNU
rust_arch_env_build:
- X86_64_UNKNOWN_LINUX_GNU
rust_default_cc:
- powerpc64le-conda-linux-gnu-cc
rust_default_cc_build:
- x86_64-conda-linux-gnu-cc
target_platform:
- linux-64
version:
- 1.55.0
zip_keys:
- - cdt_name
  - docker_image
- - cross_target_platform
  - rust_arch
  - rust_arch_env
  - rust_default_cc
  - MACOSX_SDK_VERSION
  - MACOSX_DEPLOYMENT_TARGET
- - version
  - channel_sources
  - channel_targets
