MACOSX_DEPLOYMENT_TARGET:
- '11.0'
MACOSX_SDK_VERSION:
- '11.0'
cdt_name:
- cos6
channel_sources:
- conda-forge/label/rust_dev,conda-forge
channel_targets:
- conda-forge rust_dev
cross_target_platform:
- osx-arm64
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
rust_arch:
- aarch64-apple-darwin
rust_arch_env:
- AARCH64_APPLE_DARWIN
rust_arch_env_build:
- X86_64_UNKNOWN_LINUX_GNU
rust_default_cc:
- arm64-apple-darwin20.0.0-clang
rust_default_cc_build:
- x86_64-conda-linux-gnu-cc
target_platform:
- linux-64
version:
- 1.63.0
zip_keys:
- - cross_target_platform
  - rust_arch
  - rust_arch_env
  - rust_default_cc
  - MACOSX_SDK_VERSION
  - MACOSX_DEPLOYMENT_TARGET
- - version
  - channel_sources
  - channel_targets
