MACOSX_DEPLOYMENT_TARGET:
- '11.0'
MACOSX_SDK_VERSION:
- '11.0'
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cross_target_platform:
- osx-arm64
macos_machine:
- x86_64-apple-darwin13.4.0
rust_arch:
- aarch64-apple-darwin
rust_arch_env:
- AARCH64_APPLE_DARWIN
rust_arch_env_build:
- X86_64_APPLE_DARWIN
rust_default_cc:
- arm64-apple-darwin20.0.0-clang
rust_default_cc_build:
- x86_64-apple-darwin13.4.0-clang
target_platform:
- osx-64
version:
- 1.58.0
zip_keys:
- - cross_target_platform
  - rust_arch
  - rust_arch_env
  - rust_default_cc
  - MACOSX_SDK_VERSION
  - MACOSX_DEPLOYMENT_TARGET
- - version
  - channel_sources
  - channel_targets
