MACOSX_DEPLOYMENT_TARGET:
- '10.9'
MACOSX_SDK_VERSION:
- '10.9'
channel_sources:
- conda-forge/label/rust_dev,conda-forge
channel_targets:
- conda-forge rust_dev
cross_target_platform:
- osx-64
macos_machine:
- arm64-apple-darwin20.0.0
rust_arch:
- x86_64-apple-darwin
rust_arch_env:
- X86_64_APPLE_DARWIN
rust_arch_env_build:
- AARCH64_APPLE_DARWIN
rust_default_cc:
- x86_64-apple-darwin13.4.0-clang
rust_default_cc_build:
- arm64-apple-darwin20.0.0-clang
target_platform:
- osx-arm64
version:
- 1.63.0
zip_keys:
- - cross_target_platform
  - rust_arch
  - rust_arch_env
  - rust_default_cc
  - MACOSX_SDK_VERSION
  - MACOSX_DEPLOYMENT_TARGET
- - version
  - channel_sources
  - channel_targets
